name: End-to-end regression
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run regression
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/*.cy.js