name: End-to-end schedule
on: 
  schedule:
    # runs tests every day at 12.00 PM WIB
    - cron: '0 17 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run schedule
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/*.cy.js